### ISSUE TITLE
`vim.tressitter.query.get_node_text` deprecation

### ISSUE THREAD

**Issue by adrian5** [jghauser/follow-md-links.nvim#13]
With **nvim 0.9** stable, there now is a deprecation warning from the API:

```
vim.treesitter.query.get_node_text() is deprecated, use vim.treesitter.get_node_text() instead. :help deprecated
This feature will be removed in Nvim version 0.10
```

A straight forward adaptation that retains backward compatibility can be seen e.g. [here](https://github.com/theHamsta/nvim-dap-virtual-text/pull/54/files):

```lua
local get_node_text = vim.treesitter.get_node_text or vim.treesitter.query.get_node_text
```

It should be straight forward to do adapt `follow-md-links.lua` accordingly.

**Comment by jghauser** [comment]
This should be fixed thanks to the above PR! Feel free to re-open if you run into issues
