### ISSUE TITLE
[ask] How to use this plugin?

### ISSUE THREAD

**Issue by tempegarit** [jghauser/follow-md-links.nvim#2]
Hi! I like the features this plugin offers but I don't know how to use it. Could you add a tutorial on how to use this plugin?

Thanks.

**Comment by jghauser** [comment]
Hey @tempegarit! I've updated the plugin to use the default nvim-treesitter markdown parser (which makes it much easier to install) and added some additional information in the README. If this doesn't clear things up, do tell me! :)

**Comment by tempegarit** [comment]
Hi @jghauser. This is what I think this plugin do:

I have a file named `hello.md`. I write `[world](./earth/world.md)` in it. When I put the cursor on the letter `e` in `earth` (or wherever it is as long as it is in the link), it will open the `world.md` file.

Do I understand it correctly?

**Comment by jghauser** [comment]
Yes, that is correct! You move your cursor on a link, press enter, and it opens the linked file.

**Comment by tempegarit** [comment]
Ok. Thanks for this great plugin mate!

**Comment by jghauser** [comment]
No problem, happy to hear the plugin is useful to someone!
